apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-design-auth
  labels:
    app: system-design-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: system-design-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: system-design-auth
    spec:
      containers:
        - name: system-design-auth
          image: minh123456/system-design-auth
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
